return {}
-- return {
--   {
--     "neovim/nvim-lspconfig",
--     opts = {
--       servers = {
--         lexical = {
--           filetypes = { "elixir", "eelixir" },
--           cmd = {
--             "/Users/quaseninja/Documents/work/opensource/lexical/_build/dev/package/lexical/bin/start_lexical.sh",
--           },
--           settings = {
--             lexical = {
--               format = { enabled = false },
--             },
--           },
--         },
--       },
--     },
--   },
-- }
